bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r1
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r2
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r3
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r4
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r5
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r6
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r7
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r8
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r9
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r10
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r11
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r12
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r13
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r14
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r15
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r16
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r17
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r18
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r19
bedtools shuffle -incl ./genes.with.promoters -chrom -noOverlapping -i /home/impnonames.bed -g ./chromosomes > ./RandomIntervals/r20
