bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM1
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM2
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM3
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM4
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM5
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM6
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM7
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM8
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM9
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM10
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM11
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM12
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM13
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM14
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM15
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM16
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM17
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM18
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM19
bedtools intersect -wa -a /goodfilewithASM.bedgraph -b /randomintervals/r1 > ./randomwithASM/randomASM20
